version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards_provider.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
